version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - kwhetstone
  - MarkEWaite
  labels:
  - dependencies
  ignore:
  # the dependency is actually provided by the Web container, hence it is aligned with Jetty. See https://github.com/jenkinsci/jenkins/pull/5211
  - dependency-name: "javax.servlet:javax.servlet-api"
